#!/bin/sh

soul=${SOUL:-soul}
xdg_config_home=${XDG_CONFIG_HOME:-$HOME/.config/}

if [ ! -f $xdg_config_home/soul/soul.conf ] ; then

        set $(zenity --title="Enter Your credentials for Netsoul" \
		--forms --text="Enter Your credentials for Netsoul" \
		--add-entry=login \
		--add-password=pwd_socks --separator=' ')
	login=$1
	password=$2

	mkdir -p $xdg_config_home/soul

	cat <<EOF > $xdg_config_home/soul/soul.conf
server = ns-server.epita.fr
port = 4242
user = $login
password = $password
EOF

fi

exec $soul
